### PR TITLE
8240567: MethodTooLargeException thrown while creating a jlink image

### PR DESCRIPTION
**Pull request by koppor**
Follow-up to https://github.com/JabRef/jdk/pull/3

This ports https://github.com/JabRef/jdk/pull/2 to a JDK21 version.

### CODE REVIEW

**Comment by koppor** [comment]
Triggered workflow with `linux-x64, macos, macos-x64, macos-aarch64, windows-x64`

**Comment by Siedlerchr** [comment]
jtreg error refs https://bugs.openjdk.org/browse/CODETOOLS-7903482

**Comment by Siedlerchr** [comment]
For the jtreg
https://github.com/openjdk/jdk/commit/8aad881e803fddc26f45270f779ff0c0e5a095d8

**Comment by koppor** [comment]
Do we need to comment somewhere and ask for a backport to jdk21?

**Comment by koppor** [comment]
I will just cherry pick to our internal jdk21 repo

**Pull request closed without merging**
